server:
  port: ${PORT:10000}

spring:
  application:
    name: prueba

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000
      validation-timeout: 5000
      data-source-properties:
        ssl: true
        sslmode: require
        prepareThreshold: 0

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
